name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting a bug! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Set configuration '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: cloud-provider
    attributes:
      label: Cloud Provider
      description: Which cloud provider were you using?
      options:
        - AWS
        - Azure
        - GCP
        - Hetzner Cloud
        - DigitalOcean
        - libvirt/KVM
        - Not applicable
    validations:
      required: true

  - type: input
    id: db-version
    attributes:
      label: Database Version
      description: Which Exasol database version were you deploying?
      placeholder: e.g., exasol-2025.1.8
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment Information
      description: |
        Please provide information about your environment:
      value: |
        - OS: [e.g., Ubuntu 22.04, macOS 14.0]
        - Bash version: [run `bash --version`]
        - OpenTofu/Terraform version: [run `tofu version` or `terraform version`]
        - Ansible version: [run `ansible --version`]
        - Deployer version: [run `./exasol version`]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: |
        Please include relevant log output. You can find logs in:
        - Deployment logs: `<deployment-dir>/logs/`
        - Terraform logs: `<deployment-dir>/.terraform/`
        - System logs: `journalctl` output from affected nodes
      placeholder: Paste relevant log output here...
      render: shell
    validations:
      required: false

  - type: textarea
    id: config
    attributes:
      label: Configuration Files
      description: |
        Please share relevant configuration (remove sensitive information):
        - `variables.auto.tfvars` (redact sensitive values)
        - Command line used
        - Any custom modifications
      placeholder: Paste configuration here...
      render: shell
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm you have completed these steps
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have included all relevant information above
          required: true
        - label: I have removed or redacted any sensitive information (passwords, API keys, etc.)
          required: true
        - label: I can reproduce this issue consistently
          required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, such as screenshots, workarounds, or related issues.
      placeholder: Any additional information...
    validations:
      required: false